### ISSUE TITLE
Belongs to many associations don't work

### ISSUE THREAD

**Issue by cesar2064** [trailsjs/trailpack-sequelize#12]
I have the following models:

User.js:

```
module.exports = class User extends Model {
  static config (app,Sequelize) {
    return {
       options: {
         classMethods: {
           //If you need associations, put them here
           associate: (models) => {
             //More information about associations here : http://docs.sequelizejs.com/en/latest/docs/associations/
             models.User.belongsToMany(models.Role, {
               as: 'Roles',
               onDelete: 'CASCADE',
               through:{
                model: models.UserRole,
                unique:false
               },
               foreignKey: "user_id"
             })
           }
         }
       }
     }
  }

  static schema (app,Sequelize) {
    return {
         name: { type: Sequelize.STRING, allowNull: false },
         password: Sequelize.STRING,
         displayName: Sequelize.STRING
    }
  }
}
```

Role.js
```
module.exports = class Role extends Model {

  static config () {
    return {
       options: {
         classMethods: {
           //If you need associations, put them here
           associate: (models) => {
             //More information about associations here : http://docs.sequelizejs.com/en/latest/docs/associations/
             models.Role.belongsToMany(models.User, {
               as: 'Users',
               onDelete: 'CASCADE',
               through:{
                model: models.UserRole,
                unique:false
               },
               foreignKey: "role_id"
             })
           }
         }
       }
     }
  }

  static schema (app,Sequelize) {
    return {
         name: { type: Sequelize.STRING, allowNull: false }
    }
  }
}

```
UserRole.js

```
module.exports = class UserRole extends Model {

  static config () {
  }

  static schema (app,Sequelize) {
    return {
      role_id: {
        type: Sequelize.INTEGER,
        references: 'role',
        referencesKey: 'id',
        allowNull: false
      },
      user_id:{
        type: Sequelize.INTEGER,
        references: 'user',
        referencesKey: 'id',
        allowNull: false
      }
    }
  }
}

```

and I had the following error after the app starts:

```
SequelizeDatabaseError:  relation  «role» does not exist
    at Query.formatError (D:\Proyectos\covead-core\node_modules\sequelize\lib\dialects\postgres\query.js:357:14)
    at .<anonymous> (D:\Proyectos\covead-core\node_modules\sequelize\lib\dialects\postgres\query.js:88:19)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Query.handleError (D:\Proyectos\covead-core\node_modules\pg\lib\query.js:108:8)
    at .<anonymous> (D:\Proyectos\covead-core\node_modules\pg\lib\client.js:171:26)
    at emitOne (events.js:96:13)
    at emit (events.js:188:7)
    at Socket.<anonymous> (D:\Proyectos\covead-core\node_modules\pg\lib\connection.js:109:12)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:172:18)
    at Socket.Readable.push (_stream_readable.js:130:10)
    at TCP.onread (net.js:542:20)
error: The application did not boot successfully.
error: Try increasing the loglevel to "debug" to learn more
```

**Comment by jaumard** [comment]
Maybe it's `Roles` as  you set `as: 'Roles',`  ? I think it's a sequelize configuration not a trailpack problem

**Comment by cesar2064** [comment]
I think the problem is the order in which tables are being created:

```
Executing (default): SET FOREIGN_KEY_CHECKS = 0
Executing (default): SET FOREIGN_KEY_CHECKS = 0
Executing (default): SET FOREIGN_KEY_CHECKS = 0
Executing (default): DROP TABLE IF EXISTS "user" CASCADE;
Executing (default): DROP TABLE IF EXISTS "role" CASCADE;
Executing (default): DROP TABLE IF EXISTS "userrole" CASCADE;
Executing (default): CREATE TABLE IF NOT EXISTS "userrole" ("role_id" INTEGER NOT NULL REFERENCES "role" ("id"), "user_id" INTEGER NOT NULL REFERENCES "user" ("id"), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, "UserId
" INTEGER  REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE, "RoleId" INTEGER  REFERENCES "role" ("id") ON DELETE CASCADE ON UPDATE CASCADE, PRIMARY KEY ("UserId","RoleId"));
Executing (default): CREATE TABLE IF NOT EXISTS "user" ("id"   SERIAL , "name" VARCHAR(255) NOT NULL, "password" VARCHAR(255), "displayName" VARCHAR(255), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL, "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL, PRIMARY KEY ("id")
);
error:
 SequelizeDatabaseError: relation "role" does not exist
```
The table userrole has references to user and role tables, but it was created before the tables user and role.

**Comment by jaumard** [comment]
Hum maybe the problem is here then https://github.com/trailsjs/trailpack-sequelize/blob/master/index.js#L80 not on the creations but on migrations. You set it to drop ?

**Comment by cesar2064** [comment]
Yeah, right I set it to drop.

**Comment by jaumard** [comment]
Set it to alter for now and I'll see how fix this ^^ or if you know how fit it PRs are welcome :D

**Comment by cesar2064** [comment]
The problem here  is how can you priorize the table creation.

**Comment by jaumard** [comment]
Yeah it will be better to do like knex https://github.com/trailsjs/trailpack-knex/blob/master/index.js#L70 first remove models that need to, then only call `alterDB` https://github.com/trailsjs/trailpack-sequelize/blob/master/api/services/SchemaMigrationService.js#L51 sequelize will do all the job for us ^^ 

Like this we doesn't have to develop a prioritize model drop/create queue ^^

**Comment by cesar2064** [comment]
Maybe if you creates the fks after the tables creation

**Comment by jaumard** [comment]
Can you try this (manually on `index.js` of the trailpack) : 

```

  migrate() {
    const SchemaMigrationService = this.app.services.SchemaMigrationService
    const database = this.app.config.database

    if (database.models.migrate == 'none') return

    return Promise.all(
      _.map(this.connections, connection => {

        if (database.models.migrate == 'drop') {
          return SchemaMigrationService.dropDB(connection)
        }
        else if (database.models.migrate == 'alter') {
          return SchemaMigrationService.alterDB(connection)
        }
      })
    )
  }

```

I'll do the PR if it's working :)

**Comment by cesar2064** [comment]
It works!!
